import { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import qs from "qs";
import ArticleList from "../../components/Blog/ArticleList";
import Pagination from "../../components/Blog/Pagination";
import Tabs from "../../components/Blog/Tabs";
import { fetchArticles, fetchCategories } from "../../http";
import {
  IArticle,
  ICategory,
  ICollectionResponse,
  IPagination,
  IQueryOptions,
} from "../../types";
import { capitalizeFirstLatter, debounce, makeCategory } from "../../utils";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: {
    items: IArticle[];
    pagination: IPagination;
  };
  slug: string;
}

const category = ({ categories, articles, slug }: IPropTypes) => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter();
  const { page, pageCount } = articles.pagination;

  const handleSearch = (query: string) => {
    router.push(`/category/${slug}/?search=${query}`);
  };

  const formattedCategory = () => {
    return capitalizeFirstLatter(makeCategory(slug));
  };
  return (
    <>
      <Head>
        <title>Coders Blog {formattedCategory()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Tabs */}
      <Tabs
        categories={categories.items}
        handleOnSearch={debounce(handleSearch, 500)}
      />

      {/* Articles */}
      <ArticleList articles={articles.items} />

      {/* Pagination */}
      <Pagination
        page={page}
        pageCount={pageCount}
        redirectUrl={`/category/${slug}`}
      />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  // options
  const options: Partial<IQueryOptions> = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
    filters: {
      category: {
        slug: query.category,
      },
    },
    pagination: {
      page: query.page ? +query.page : 1,
      pageSize: 1,
    },
  };

  if (query.search) {
    options.filters = {
      ...options.filters,
      Title: {
        $containsi: query.search,
      },
    };
  }

  const queryString = qs.stringify(options);

  // fetch categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  // fetch articles
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticles(queryString);

  return {
    props: {
      categories: {
        items: categories.data,
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },
      slug: query.category,
    },
  };
};

export default category;
